### ISSUE TITLE
default network_sync_base_url  seems have data outdate, any other suggestions for this 

### ISSUE THREAD

**Issue by BlueShells** [ethpandaops/ethereum-package#647]
Hi I try to create a shadow fork of holeksy  wth default setting of sync_base_url : https://ethpandaops-ethereum-node-snapshots.ams3.digitaloceanspaces.com/

everything works ,but the data is far behand the current holesky , I didn't have snapshot local, any suggestion of which other url I could use to sync data ?

**Comment by skylenet** [comment]
Hi @BlueShells. Sorry for the late reply. We had a bug on our snapshot instances that caused the snapshot to not be executed. This bug should be fixed now and more recent snapshots should appear in the comming 1-2 days for the sepolia and holesky networks. For now we'll have snapshots for geth,reth,nethermind and besu. We're waiting for erigon to make a release on their v3 to also include them on our snapshots.
