### ISSUE TITLE
Step by Step manual README needed 

### ISSUE THREAD

**Issue by BlueShells** [ethpandaops/ethereum-package#728]
Hi I am trying to follow the guide to shadow fork mainnet/sepolia/testnet to do test 
Kurtosis is easy to start , one command will do the work， but this make it hard to debug when run into issue (I run into issue a few times , the repo keep changes everyday ), also  hard to hack some change like ：
I want to shadown mainnet to do test ,but the contract on mainnet is multi sig , so I need to hack to change the owner from multisig to EOA ,so I could do contract related test on the shadow fork , but currently its hard to hack this 

so , if someone could provide another doc to split the what Kurtosis like : 
* how to Generate Execution Layer (EL) & Consensus Layer (CL) genesis information using [the Ethereum genesis generator](https://github.com/ethpandaops/ethereum-genesis-generator).
* how to Configure & bootstrap a network of Ethereum nodes of n size using the genesis data generated above
* how to Spin up a [transaction spammer](https://github.com/MariusVanDerWijden/tx-fuzz) to send fake transactions to the network 
....

this will help to debug issue and help us understand how this Kurtosis works 

thanks

**Comment by barnabasbusa** [comment]
I do not see how a step by step manual is needed for the ethereum-package repository. 
We have a quick note that helps you understand how shadowforks supposed to work: https://notes.ethereum.org/@parithosh/shadowfork-tutorial
Each project like the ethereum genesis generator and transaction spammer has an individual readme that describes how the given tool is supposed to work, and thus I don't understand which parts are you missing. 
As mentioned in the other issue as well, we do not plan to support public mainnet shadowforks using our snapshots, as these would require immense amount of bandwidth.
