### ISSUE TITLE
Request for information about the policy according to future updates

### ISSUE THREAD

**Issue by entertainment-veks** [ethpandaops/ethereum-package#756]
Hello! Currently my team launches a start-up and we need to use L2 private network. 
As far as Lighthouse is not supporting private networks anymore and in open words recommend to use Kurtosis for private networks instead: https://github.com/sigp/lighthouse/issues/6123.
We currently thinking about choosing kurtosis as our production approach, but a single thing our strategy team worries about is upgrading network with future forks.

How would we be able to merge future forks with Kurtosis?
Thanks!

**Comment by barnabasbusa** [comment]
Kurtosis is not meant to be ran as a production software. We plan to keep the ethereum-package as up to date as possible with future ethereum forks. Ideally none of the future releases will break anything major, however there is no assurance for this.
