### ISSUE TITLE
bandwidth and resources usage peaks

### ISSUE THREAD

**Issue by lzmrd** [ethpandaops/ethereum-package#759]
I deployed a new blockchain on a VM as in example from: [https://geth.ethereum.org/docs/fundamentals/kurtosis#prerequisites](https://geth.ethereum.org/docs/fundamentals/kurtosis#prerequisites)
It works as I would but there are still some issues. I'm not a great sysadmin yet so I cannot understand what is going on and what is happening.

It often experience bandwidth peaks from requests coming from unkown IPs.
It often experience resources peaks.

I attach two screenshots coming from command `htop`:
![image](https://github.com/user-attachments/assets/b0b88e71-181e-4508-979c-9a0bcb23da16)

and from command `iftop`:
![image](https://github.com/user-attachments/assets/13fb0470-c886-4b4f-8af1-b7fdd15873df)

Is that a regular behaviour or is there something weird?

**Comment by barnabasbusa** [comment]
I'm sorry but I don't see anything out of the ordinary?
