### ISSUE TITLE
Change chain ticker and supply

### ISSUE THREAD

**Issue by roccomuso** [ethpandaops/ethereum-package#777]
Is it possible to have prefunded accounts with a different ticker/coin ?

>  prefunded_accounts: '{"0x25941dC771bB64514Fc8abBce970307Fb9d477e9": {"balance": "10ETH"}, "0x4107be99052d895e3ee461C685b042Aa975ab5c0": {"balance": "1ETH"}}'

Like what if I want to spawn my own private blockchain and change ticker or supply? hence avoid calling it ETH

**Comment by barnabasbusa** [comment]
No. This is an ethereum package. If you want something else, you will have to fork this project. 

This project focuses on Ethereum.
