### ISSUE TITLE
how to fix the port for full_beaconchain_explorer

### ISSUE THREAD

**Issue by supernovahs** [ethpandaops/ethereum-package#801]

**Comment by barnabasbusa** [comment]
Could you describe the issue with a bit more details?

**Comment by supernovahs** [comment]
I mean every time i start a new instance, the port number for explorer changes, i want it to be consistent, or any other way so i can add the port address in makefile

**Comment by barnabasbusa** [comment]
For static ports please refer to the [readme](https://github.com/ethpandaops/ethereum-package/blob/main/README.md?plain=1#L921)

**Comment by supernovahs** [comment]
thanks
